/*
 * basic_renderer.h
 *
 *  Created on: Jun 21, 2017
 *      Author: sacha
 */

#ifndef SRC_CLIENT_RENDERING_RENDERERS_BASIC_RENDERER_H_
#define SRC_CLIENT_RENDERING_RENDERERS_BASIC_RENDERER_H_





#endif /* SRC_CLIENT_RENDERING_RENDERERS_BASIC_RENDERER_H_ */
